db:
  url: jdbc:mysql://localhost:3306/tour_jpa_db?verifyServerCertificate=false&useSSL=true
  driverClass: com.mysql.jdbc.Driver
  poolSize: 4
  userName: root
  password: root

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create