logging:
  level:
    root: INFO

db:
  url: jdbc:mysql://localhost:3306/tour_jdbc_db?verifyServerCertificate=false&useSSL=true
  driverClass: com.mysql.jdbc.Driver
  poolSize: 4
  userName: root
  password: root

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
